export const LEVELS = {
    N5: 'N5',
    N5_KANJI: 'N5-KANJI',
    N4_N3: 'N4-N3',
    N5_BASIC_GRAMMAR: 'N5-BASIC-GRAMMAR',
    N5_ADVANCE_GRAMMAR: 'N5-ADVANCE-GRAMMAR',
    N4_BASIC_GRAMMAR: 'N4-BASIC-GRAMMAR',
  };
  

  export  const COVERPAGE_CARD_WIDTH = 360;



